// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuiPLsY-d6f-oLFxW6M0jG47UaCLP-dK0',
    appId: '1:1004687713172:web:85b7dee466686592bfe581',
    messagingSenderId: '1004687713172',
    projectId: 'sk-amna',
    authDomain: 'sk-amna.firebaseapp.com',
    storageBucket: 'sk-amna.firebasestorage.app',
    measurementId: 'G-M64KBZ1CGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7tBM8buLkOczqlxS5WURCItRujukp3w',
    appId: '1:1004687713172:android:242431457ea80d3abfe581',
    messagingSenderId: '1004687713172',
    projectId: 'sk-amna',
    storageBucket: 'sk-amna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXIV96Qr9nTZW0rct4vk5bHeQxwJDGB3k',
    appId: '1:1004687713172:ios:49cb63a8a71e6817bfe581',
    messagingSenderId: '1004687713172',
    projectId: 'sk-amna',
    storageBucket: 'sk-amna.firebasestorage.app',
    iosBundleId: 'com.example.skAmna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXIV96Qr9nTZW0rct4vk5bHeQxwJDGB3k',
    appId: '1:1004687713172:ios:49cb63a8a71e6817bfe581',
    messagingSenderId: '1004687713172',
    projectId: 'sk-amna',
    storageBucket: 'sk-amna.firebasestorage.app',
    iosBundleId: 'com.example.skAmna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuiPLsY-d6f-oLFxW6M0jG47UaCLP-dK0',
    appId: '1:1004687713172:web:555e4c9132f1b45ebfe581',
    messagingSenderId: '1004687713172',
    projectId: 'sk-amna',
    authDomain: 'sk-amna.firebaseapp.com',
    storageBucket: 'sk-amna.firebasestorage.app',
    measurementId: 'G-X5ECLJ5CDT',
  );
}
