// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwMa8G1aFKrksycQBC0iVLwVSOUxGMSA',
    appId: '1:265206840779:web:00102f976a5fcd65824a4e',
    messagingSenderId: '265206840779',
    projectId: 'loctel-tracker',
    authDomain: 'loctel-tracker.firebaseapp.com',
    storageBucket: 'loctel-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH2LXdI29XKtJOyE7rgG0ljyeep7TP8UY',
    appId: '1:265206840779:android:3bf31611bbe493fe824a4e',
    messagingSenderId: '265206840779',
    projectId: 'loctel-tracker',
    storageBucket: 'loctel-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWQQzo4mb0o42_3u_Q_sdGisAU2fwE3g',
    appId: '1:265206840779:ios:e4eddc9b6fe114c1824a4e',
    messagingSenderId: '265206840779',
    projectId: 'loctel-tracker',
    storageBucket: 'loctel-tracker.firebasestorage.app',
    iosBundleId: 'com.example.loctelViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeWQQzo4mb0o42_3u_Q_sdGisAU2fwE3g',
    appId: '1:265206840779:ios:e4eddc9b6fe114c1824a4e',
    messagingSenderId: '265206840779',
    projectId: 'loctel-tracker',
    storageBucket: 'loctel-tracker.firebasestorage.app',
    iosBundleId: 'com.example.loctelViewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqwMa8G1aFKrksycQBC0iVLwVSOUxGMSA',
    appId: '1:265206840779:web:504fa38312f6fad7824a4e',
    messagingSenderId: '265206840779',
    projectId: 'loctel-tracker',
    authDomain: 'loctel-tracker.firebaseapp.com',
    storageBucket: 'loctel-tracker.firebasestorage.app',
  );
}
